//@CodeCopy
namespace SupportChat.Common.Enums
{
    public enum LanguageCode
    {
        af, // Afrikaans
        ar, // Arabisch
        bg, // Bulgarisch
        bn, // Bengalisch
        bo, // Tibetisch
        ca, // Katalanisch
        cs, // Tschechisch
        cy, // Walisisch
        da, // Dänisch
        de, // Deutsch
        el, // Griechisch
        en, // Englisch
        eo, // Esperanto
        es, // Spanisch
        et, // Estnisch
        eu, // Baskisch
        fa, // Persisch
        fi, // Finnisch
        fr, // Französisch
        ga, // Irisch
        gl, // Galicisch
        gu, // Gujarati
        he, // Hebräisch
        hi, // Hindi
        hr, // Kroatisch
        hu, // Ungarisch
        hy, // Armenisch
        id, // Indonesisch
        _is, // Isländisch
        it, // Italienisch
        ja, // Japanisch
        ka, // Georgisch
        kn, // Kannada
        ko, // Koreanisch
        la, // Latein
        lt, // Litauisch
        lv, // Lettisch
        mk, // Mazedonisch
        ml, // Malayalam
        mn, // Mongolisch
        mr, // Marathi
        ms, // Malaiisch
        mt, // Maltesisch
        ne, // Nepalesisch
        nl, // Niederländisch
        no, // Norwegisch
        pa, // Panjabi
        pl, // Polnisch
        pt, // Portugiesisch
        ro, // Rumänisch
        ru, // Russisch
        sa, // Sanskrit
        sk, // Slowakisch
        sl, // Slowenisch
        sq, // Albanisch
        sr, // Serbisch
        sv, // Schwedisch
        ta, // Tamil
        te, // Telugu
        th, // Thailändisch
        tl, // Tagalog
        tr, // Türkisch
        uk, // Ukrainisch
        ur, // Urdu
        uz, // Usbekisch
        vi, // Vietnamesisch
        zh  // Chinesisch
    }
}
